# -*- coding: utf-8 -*-
"""Semana2PF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hnZ0eAOL-RunY1XwpIiigcEJKMi8FZpM
"""

# importar librerias
import math
 
 
# definir funcion
def funcuadratica( a, b, c):
 
    dis = b * b - 4 * a * c
    sqrt = math.sqrt(abs(dis))
     
    # checando la condicion del discrminante para saber si tiene solucion o no tiene solucion
    if dis > 0:
        n1=(-b + sqrt)/(2 * a)
        n2= (-b - sqrt)/(2 * a)
        return print("Raices Reales y diferentes ","\n",n1,"\n",n2)
        
     
    elif dis == 0:
        n1 = -b / (2 * a)
        return  print("Raices Reales y igales, es decir solo exisrte una raiz","\n",n1)

     
    # cando es menor a cero que no tiene solucion, es porque son raices imaginarias
    else:
        n1= - b / (2 * a), " + i", sqrt
        n2= - b / (2 * a), " - i", sqrt
        return  print("Raices Imaginarias","\n",n1,"\n", n2)

 
# Solicitar variables a, b y c 
a = input("Favor de ingresar la variable a de la funcion cuadratica: \n a: ")
b = input("Favor de ingresar la variable a de la funcion cuadratica: \n b: ")
c = input("Favor de ingresar la variable a de la funcion cuadratica: \n c: ")
 
# If a is 0, then incorrect equation
while int(a) == 0:
        a= input("Ingresa un numero que no sea cero \n a: ")
 
# Una vez que se valide que a no es cero 
funcuadratica(int(a), int(b), int(c))